language: objective-c
script:
 - "xctool -workspace Example/ViSearch.xcworkspace -scheme ViSearch-Example -sdk iphonesimulator7.0 -destination 'platform=iOS Simulator,name=iPhone 6,OS=7.0' build test"
